### ISSUE TITLE
More versions

### ISSUE THREAD

**Issue by MagicBloodFly** [wcpe/WC-Bot#1]
如果有PM版本的话我觉得会非常完美
希望会有一个PM版本的 :)

**Comment by wcpe** [comment]
我并不会php 所以无法制作pm的版本 抱歉

**Comment by wcpe** [comment]
我并不会php 所以无法制作pm的版本 抱歉

**Comment by MagicBloodFly** [comment]
没关系 很棒的插件!

**Comment by smallXueTu** [comment]
核心使用的mirai-core 这个核心是kotlin写的   php不能依赖他
